package com.deeply.gankura.config;

import java.util.HashMap;
import java.util.Map;

/**
 * 設定画面の折りたたみ見出しの表。MoulConfig のアコーディオンを引き継いだもの。
 *
 * 項目を見出しの下に入れるには、GROUP_OF にその項目の翻訳キーと見出しのキーを足す。
 * 載っていない項目は、見出しに入らずカテゴリの直下に出る。
 *
 * 見出しを増やすときは:
 *   1. ALL に見出しのキーを足す（キーの形は "gankura.config.<カテゴリ>.sep.<名前>"）
 *   2. 入れ子にするなら PARENT に親の見出しのキーを足す
 *   3. lang/en_us.json に見出しの文言（キー）と説明（キー + ".desc"）を足す
 *
 * 見出しの並び順は ModConfig の項目の並び順で決まる（最初の項目が出たところに見出しが出る）。
 */
public final class ConfigGroups {

    /** 項目の翻訳キー -> 直属の見出しのキー */
    public static final Map<String, String> GROUP_OF = new HashMap<>();

    /** 見出しのキー -> 親の見出しのキー。最上段の見出しは載っていない */
    public static final Map<String, String> PARENT = new HashMap<>();

    /** 見出しのキー。並び順は画面に出る順 */
    public static final java.util.List<String> ALL = new java.util.ArrayList<>();

    private ConfigGroups() {
    }

    static {
        items();
        groups();
    }

    private static void items() {
        GROUP_OF.put("gankura.config.combat.theEnd.showGolemStatusHud", "gankura.config.combat.theEnd.sep.golemSection");
        GROUP_OF.put("gankura.config.combat.theEnd.showLootTrackerHud", "gankura.config.combat.theEnd.sep.golemRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableDropAlerts", "gankura.config.combat.theEnd.sep.golemRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.trackedGolemDrops", "gankura.config.combat.theEnd.sep.golemRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showGolemWorldLocation_Text", "gankura.config.combat.theEnd.sep.worldLocationFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showGolemWorldLocation_Beacon", "gankura.config.combat.theEnd.sep.worldLocationFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showGolemWorldLocation_Tracer", "gankura.config.combat.theEnd.sep.worldLocationFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableStage4Title", "gankura.config.combat.theEnd.sep.stage4Folder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableStage4Sound", "gankura.config.combat.theEnd.sep.stage4Folder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableStage5Title", "gankura.config.combat.theEnd.sep.stage5Folder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableStage5Sound", "gankura.config.combat.theEnd.sep.stage5Folder");
        GROUP_OF.put("gankura.config.combat.theEnd.showStage4Duration", "gankura.config.combat.theEnd.sep.golemChatFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showDpsChat", "gankura.config.combat.theEnd.sep.golemChatFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showLootQualityChat", "gankura.config.combat.theEnd.sep.golemChatFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableDay30Alert", "gankura.config.combat.theEnd.sep.golemChatFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showDragonStatusHud", "gankura.config.combat.theEnd.sep.dragonSection");
        GROUP_OF.put("gankura.config.combat.theEnd.showDragonTrackerHud", "gankura.config.combat.theEnd.sep.dragonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableDragonDropAlerts", "gankura.config.combat.theEnd.sep.dragonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.trackedDragonDrops", "gankura.config.combat.theEnd.sep.dragonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.enableDragonSpawnAlert", "gankura.config.combat.theEnd.sep.spawnTitleFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.dragonSpawnAlerts", "gankura.config.combat.theEnd.sep.spawnTitleFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showDragonDpsChat", "gankura.config.combat.theEnd.sep.dragonChatFolder");
        GROUP_OF.put("gankura.config.combat.theEnd.showDragonLootQualityChat", "gankura.config.combat.theEnd.sep.dragonChatFolder");
        GROUP_OF.put("gankura.config.combat.spidersDen.showBroodmotherStatusHud", "gankura.config.combat.spidersDen.sep.broodmotherSection");
        GROUP_OF.put("gankura.config.combat.spidersDen.enableStage4Title", "gankura.config.combat.spidersDen.sep.broodmotherStage4Folder");
        GROUP_OF.put("gankura.config.combat.spidersDen.enableStage4Sound", "gankura.config.combat.spidersDen.sep.broodmotherStage4Folder");
        GROUP_OF.put("gankura.config.combat.spidersDen.enableStage5Title", "gankura.config.combat.spidersDen.sep.broodmotherStage5Folder");
        GROUP_OF.put("gankura.config.combat.spidersDen.enableStage5Sound", "gankura.config.combat.spidersDen.sep.broodmotherStage5Folder");
        GROUP_OF.put("gankura.config.combat.spidersDen.showBroodmotherStage4Duration", "gankura.config.combat.spidersDen.sep.broodmotherChatFolder");
        GROUP_OF.put("gankura.config.combat.spidersDen.showArachneStatusHud", "gankura.config.combat.spidersDen.sep.arachneSection");
        GROUP_OF.put("gankura.config.combat.spidersDen.showArachneWorldText", "gankura.config.combat.spidersDen.sep.arachneWorldLocationFolder");
        GROUP_OF.put("gankura.config.combat.crimsonIsle.showCrimsonLootTrackerHud", "gankura.config.combat.crimsonIsle.sep.crimsonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.crimsonIsle.enableCrimsonDropAlerts", "gankura.config.combat.crimsonIsle.sep.crimsonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.crimsonIsle.trackedCrimsonDrops", "gankura.config.combat.crimsonIsle.sep.crimsonRareDropFolder");
        GROUP_OF.put("gankura.config.combat.crimsonIsle.showCrimsonIsleWorldText", "gankura.config.combat.crimsonIsle.sep.crimsonWorldLocationFolder");
        GROUP_OF.put("gankura.config.combat.crimsonIsle.enableMagmaBossSpawnTitle", "gankura.config.combat.crimsonIsle.sep.magmaBossSection");
        GROUP_OF.put("gankura.config.farming.solveDnaAnalyzer", "gankura.config.farming.sep.dnaFolder");
        GROUP_OF.put("gankura.config.farming.dnaAnalyzerMiddleClick", "gankura.config.farming.sep.dnaFolder");
        GROUP_OF.put("gankura.config.farming.blockDnaAnalyzerClose", "gankura.config.farming.sep.dnaFolder");
        GROUP_OF.put("gankura.config.farming.hideDnaAnalyzerTooltips", "gankura.config.farming.sep.dnaFolder");
        GROUP_OF.put("gankura.config.farming.garden.showVisitorStatusHud", "gankura.config.farming.garden.sep.visitorFolder");
        GROUP_OF.put("gankura.config.farming.garden.showVisitorItems", "gankura.config.farming.garden.sep.visitorFolder");
        GROUP_OF.put("gankura.config.farming.garden.highlightVisitorOffer", "gankura.config.farming.garden.sep.visitorFolder");
        GROUP_OF.put("gankura.config.farming.garden.showVisitorArrivalTitle", "gankura.config.farming.garden.sep.visitorTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.showVisitorQueueFullTitle", "gankura.config.farming.garden.sep.visitorTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.highlightContestRewards", "gankura.config.farming.garden.sep.contestFolder");
        GROUP_OF.put("gankura.config.farming.garden.showPestStatusHud", "gankura.config.farming.garden.sep.pestFolder");
        GROUP_OF.put("gankura.config.farming.garden.showPestSpawnTitle", "gankura.config.farming.garden.sep.pestTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.showMaxPestsTitle", "gankura.config.farming.garden.sep.pestTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.showPestSoonTitle", "gankura.config.farming.garden.sep.pestTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.pestSoonSeconds", "gankura.config.farming.garden.sep.pestTitleFolder");
        GROUP_OF.put("gankura.config.farming.garden.showPestVacuumWaypoint", "gankura.config.farming.garden.sep.vacuumFolder");
        GROUP_OF.put("gankura.config.farming.garden.showPestVacuumTracer", "gankura.config.farming.garden.sep.vacuumFolder");
        GROUP_OF.put("gankura.config.farming.garden.hidePestVacuumParticles", "gankura.config.farming.garden.sep.vacuumFolder");
        GROUP_OF.put("gankura.config.farming.garden.pestVacuumSeconds", "gankura.config.farming.garden.sep.vacuumFolder");
        GROUP_OF.put("gankura.config.farming.garden.lockViewOnMousemat", "gankura.config.farming.garden.sep.mousematFolder");
        GROUP_OF.put("gankura.config.farming.garden.unlockViewOnTeleport", "gankura.config.farming.garden.sep.mousematFolder");
        GROUP_OF.put("gankura.config.farming.garden.releaseViewKeybind", "gankura.config.farming.garden.sep.mousematFolder");
        GROUP_OF.put("gankura.config.foraging.enableTreeFelledTitle", "gankura.config.foraging.sep.titleFolder");
        GROUP_OF.put("gankura.config.foraging.enableTreeMobTitle", "gankura.config.foraging.sep.titleFolder");
        GROUP_OF.put("gankura.config.foraging.enableTikiWaypoints", "gankura.config.foraging.sep.torrhusCanyonFolder");
        GROUP_OF.put("gankura.config.foraging.enableBeeheemothSpawnTitle", "gankura.config.foraging.sep.torrhusCanyonFolder");
        GROUP_OF.put("gankura.config.foraging.showCapturedCrittersHud", "gankura.config.foraging.sep.critterSafariFolder");
        GROUP_OF.put("gankura.config.foraging.enableFloorDrops", "gankura.config.foraging.sep.critterSafariFolder");
        GROUP_OF.put("gankura.config.foraging.enableBeeNestWaypoints", "gankura.config.foraging.sep.honeybugFolder");
        GROUP_OF.put("gankura.config.foraging.hideBeeNestsWhenCaptured", "gankura.config.foraging.sep.honeybugFolder");
        GROUP_OF.put("gankura.config.foraging.enableSafariFishHighlight", "gankura.config.foraging.sep.scrappyFolder");
        GROUP_OF.put("gankura.config.foraging.hideSafariFishWhenCaptured", "gankura.config.foraging.sep.scrappyFolder");
        GROUP_OF.put("gankura.config.foraging.enableRockmiteMoundHighlight", "gankura.config.foraging.sep.rockmiteFolder");
        GROUP_OF.put("gankura.config.foraging.hideRockmiteMoundsWhenCaptured", "gankura.config.foraging.sep.rockmiteFolder");
        GROUP_OF.put("gankura.config.foraging.enableWumpaSpawnTitle", "gankura.config.foraging.sep.wumpaFolder");
        GROUP_OF.put("gankura.config.foraging.enableWumpaCapsuleMessage", "gankura.config.foraging.sep.wumpaFolder");
        GROUP_OF.put("gankura.config.foraging.enableWumpaWaypoint", "gankura.config.foraging.sep.wumpaFolder");
        GROUP_OF.put("gankura.config.foraging.enableDoomspiralCapsuleMessage", "gankura.config.foraging.sep.doomspiralFolder");
        GROUP_OF.put("gankura.config.foraging.enableMacawSpawnTitle", "gankura.config.foraging.sep.macawFolder");
        GROUP_OF.put("gankura.config.fishing.showBiteCountdownHud", "gankura.config.fishing.sep.fishingHudFolder");
        GROUP_OF.put("gankura.config.fishing.showBaitHud", "gankura.config.fishing.sep.fishingHudFolder");
        GROUP_OF.put("gankura.config.fishing.shortenSeaCreatureMessage", "gankura.config.fishing.sep.fishingChatFolder");
        GROUP_OF.put("gankura.config.fishing.showBaitLowAlert", "gankura.config.fishing.sep.baitLowAlertFolder");
        GROUP_OF.put("gankura.config.fishing.baitLowThreshold", "gankura.config.fishing.sep.baitLowAlertFolder");
        GROUP_OF.put("gankura.config.fishing.showCastTimer", "gankura.config.fishing.sep.castTimerFolder");
        GROUP_OF.put("gankura.config.fishing.castTimerOnLiquidTouch", "gankura.config.fishing.sep.castTimerFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotGuess", "gankura.config.fishing.sep.hotspotGuessFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotTracer", "gankura.config.fishing.sep.hotspotGuessFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotGoneTitle", "gankura.config.fishing.sep.hotspotFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotCircle", "gankura.config.fishing.sep.hotspotCircleFolder");
        GROUP_OF.put("gankura.config.fishing.hideHotspotParticles", "gankura.config.fishing.sep.hotspotCircleFolder");
        GROUP_OF.put("gankura.config.fishing.sharedHotspotPerks", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotFoundTitle", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.playHotspotFoundSound", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotFoundWaypoint", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.showHotspotFoundTracer", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.hotspotFoundSeconds", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.shareHotspot", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.hotspotShareChannel", "gankura.config.fishing.sep.hotspotFoundFolder");
        GROUP_OF.put("gankura.config.fishing.replaceLavaTexture", "gankura.config.fishing.sep.lavaTextureFolder");
        GROUP_OF.put("gankura.config.fishing.hideLavaFog", "gankura.config.fishing.sep.lavaTextureFolder");
        GROUP_OF.put("gankura.config.fishing.lavaTextureArea", "gankura.config.fishing.sep.lavaTextureFolder");
        GROUP_OF.put("gankura.config.fishing.showGoldenFishTimer", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.fishing.highlightGoldenFish", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.fishing.tracerGoldenFish", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.fishing.warnGoldenFishRod", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.fishing.goldenFishRodWarningSeconds", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.fishing.goldfinShardLevel", "gankura.config.fishing.sep.goldenFishFolder");
        GROUP_OF.put("gankura.config.mining.highlightCompletedCommissions", "gankura.config.mining.sep.commissionFolder");
        GROUP_OF.put("gankura.config.mining.showGemstoneCommissionWaypoints", "gankura.config.mining.sep.commissionFolder");
        GROUP_OF.put("gankura.config.mining.showCorpseWaypoints", "gankura.config.mining.sep.corpseFolder");
        GROUP_OF.put("gankura.config.mining.showCorpseTracer", "gankura.config.mining.sep.corpseFolder");
        GROUP_OF.put("gankura.config.mining.showVanguardTitle", "gankura.config.mining.sep.corpseFolder");
        GROUP_OF.put("gankura.config.mining.showCorpseProfit", "gankura.config.mining.sep.corpseFolder");
        GROUP_OF.put("gankura.config.mining.solveWishingCompass", "gankura.config.mining.sep.wishingCompassFolder");
        GROUP_OF.put("gankura.config.mining.showWishingCompassWaypoint", "gankura.config.mining.sep.wishingCompassFolder");
        GROUP_OF.put("gankura.config.generalHud.showEquipmentHud", "gankura.config.generalHud.sep.armorHudFolder");
        GROUP_OF.put("gankura.config.generalHud.equipmentHudOrientation", "gankura.config.generalHud.sep.armorHudFolder");
        GROUP_OF.put("gankura.config.generalHud.showGearHud", "gankura.config.generalHud.sep.equipmentHudFolder");
        GROUP_OF.put("gankura.config.generalHud.gearHudOrientation", "gankura.config.generalHud.sep.equipmentHudFolder");
        GROUP_OF.put("gankura.config.generalHud.showYawPitchHud", "gankura.config.generalHud.sep.yawPitchHudFolder");
        GROUP_OF.put("gankura.config.generalHud.yawPrecision", "gankura.config.generalHud.sep.yawPitchHudFolder");
        GROUP_OF.put("gankura.config.generalHud.pitchPrecision", "gankura.config.generalHud.sep.yawPitchHudFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsTheEnd", "gankura.config.mobVisuals.sep.theEndFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllTheEnd", "gankura.config.mobVisuals.sep.theEndFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllTheEnd", "gankura.config.mobVisuals.sep.theEndFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSpidersDen", "gankura.config.mobVisuals.sep.spidersDenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSpidersDen", "gankura.config.mobVisuals.sep.spidersDenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSpidersDen", "gankura.config.mobVisuals.sep.spidersDenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsCrimsonIsle", "gankura.config.mobVisuals.sep.crimsonIsleFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllCrimsonIsle", "gankura.config.mobVisuals.sep.crimsonIsleFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllCrimsonIsle", "gankura.config.mobVisuals.sep.crimsonIsleFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsCrystalHollows", "gankura.config.mobVisuals.sep.crystalHollowsFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllCrystalHollows", "gankura.config.mobVisuals.sep.crystalHollowsFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllCrystalHollows", "gankura.config.mobVisuals.sep.crystalHollowsFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsMoongladeMarsh", "gankura.config.mobVisuals.sep.moongladeMarshFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllMoongladeMarsh", "gankura.config.mobVisuals.sep.moongladeMarshFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllMoongladeMarsh", "gankura.config.mobVisuals.sep.moongladeMarshFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsTorrhusCanyon", "gankura.config.mobVisuals.sep.torrhusCanyonFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllTorrhusCanyon", "gankura.config.mobVisuals.sep.torrhusCanyonFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllTorrhusCanyon", "gankura.config.mobVisuals.sep.torrhusCanyonFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsLotusAtoll", "gankura.config.mobVisuals.sep.lotusAtollFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllLotusAtoll", "gankura.config.mobVisuals.sep.lotusAtollFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllLotusAtoll", "gankura.config.mobVisuals.sep.lotusAtollFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsGlaciteMineshaft", "gankura.config.mobVisuals.sep.glaciteMineshaftFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllGlaciteMineshaft", "gankura.config.mobVisuals.sep.glaciteMineshaftFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllGlaciteMineshaft", "gankura.config.mobVisuals.sep.glaciteMineshaftFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsGarden", "gankura.config.mobVisuals.sep.gardenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllGarden", "gankura.config.mobVisuals.sep.gardenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllGarden", "gankura.config.mobVisuals.sep.gardenFolder");
        GROUP_OF.put("gankura.config.mobVisuals.hideCapturedCritters", "gankura.config.mobVisuals.sep.hideCapturedFolder");
        GROUP_OF.put("gankura.config.mobVisuals.keepShownSafariCavern", "gankura.config.mobVisuals.sep.keepShownFolder");
        GROUP_OF.put("gankura.config.mobVisuals.keepShownSafariForest", "gankura.config.mobVisuals.sep.keepShownFolder");
        GROUP_OF.put("gankura.config.mobVisuals.keepShownSafariHaunted", "gankura.config.mobVisuals.sep.keepShownFolder");
        GROUP_OF.put("gankura.config.mobVisuals.keepShownSafariIcy", "gankura.config.mobVisuals.sep.keepShownFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSafariCavern", "gankura.config.mobVisuals.sep.safariCavernFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSafariCavern", "gankura.config.mobVisuals.sep.safariCavernFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSafariCavern", "gankura.config.mobVisuals.sep.safariCavernFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSafariForest", "gankura.config.mobVisuals.sep.safariForestFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSafariForest", "gankura.config.mobVisuals.sep.safariForestFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSafariForest", "gankura.config.mobVisuals.sep.safariForestFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSafariHaunted", "gankura.config.mobVisuals.sep.safariHauntedFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSafariHaunted", "gankura.config.mobVisuals.sep.safariHauntedFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSafariHaunted", "gankura.config.mobVisuals.sep.safariHauntedFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSafariIcy", "gankura.config.mobVisuals.sep.safariIcyFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSafariIcy", "gankura.config.mobVisuals.sep.safariIcyFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSafariIcy", "gankura.config.mobVisuals.sep.safariIcyFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableSeaCreatureTitle", "gankura.config.mobVisuals.sep.seaCreatureFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableSeaCreatureSound", "gankura.config.mobVisuals.sep.seaCreatureFolder");
        GROUP_OF.put("gankura.config.mobVisuals.targetsSeaCreature", "gankura.config.mobVisuals.sep.seaCreatureFolder");
        GROUP_OF.put("gankura.config.mobVisuals.enableAllSeaCreature", "gankura.config.mobVisuals.sep.seaCreatureFolder");
        GROUP_OF.put("gankura.config.mobVisuals.disableAllSeaCreature", "gankura.config.mobVisuals.sep.seaCreatureFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableInventoryTweaks", "gankura.config.interfaceSettings.sep.betterInventoryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideInventoryEffects", "gankura.config.interfaceSettings.sep.betterInventoryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideInventoryDim", "gankura.config.interfaceSettings.sep.betterInventoryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideRecipeBook", "gankura.config.interfaceSettings.sep.betterInventoryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableTabListTweaks", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideTabListAds", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideTabListPing", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideTabListHeads", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.compactTabList", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.fitTabColumns", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.shrinkTabList", "gankura.config.interfaceSettings.sep.tabListFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableItemTooltipTweaks", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableScrollableTooltips", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.invertTooltipScroll", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.tooltipFromTop", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableEnchantTooltipTweaks", "gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableNumericEnchantTiers", "gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableMaxEnchantChroma", "gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableBookEnchantGold", "gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.ignoreUltimateEnchants", "gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableItemPrice", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showLowestBin", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showBazaarPrice", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.bazaarPriceType", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showCraftCost", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showStackPrice", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.shortPriceNumbers", "gankura.config.interfaceSettings.sep.itemPriceFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableAuctionTweaks", "gankura.config.interfaceSettings.sep.auctionBazaarFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightBazaarOrders", "gankura.config.interfaceSettings.sep.auctionBazaarFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightOwnAuctions", "gankura.config.interfaceSettings.sep.auctionBazaarFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightUndercutAuctions", "gankura.config.interfaceSettings.sep.auctionBazaarFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableAttributeMenuTweaks", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableAttributeTierNumbers", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightAttributeProgress", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showAttributeTier", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideMaxedAttributeTier", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showAttributeCosts", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.attributeCostTarget", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.attributeCostSort", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.attributeCostRows", "gankura.config.interfaceSettings.sep.attributeFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableBestiaryMenuTweaks", "gankura.config.interfaceSettings.sep.bestiaryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableBestiaryTierNumbers", "gankura.config.interfaceSettings.sep.bestiaryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightBestiaryProgress", "gankura.config.interfaceSettings.sep.bestiaryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showBestiaryTier", "gankura.config.interfaceSettings.sep.bestiaryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideMaxedBestiaryTier", "gankura.config.interfaceSettings.sep.bestiaryFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableHuntingBoxTweaks", "gankura.config.interfaceSettings.sep.huntingBoxFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showShardsOwned", "gankura.config.interfaceSettings.sep.huntingBoxFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showShardValues", "gankura.config.interfaceSettings.sep.huntingBoxFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.shardValueRows", "gankura.config.interfaceSettings.sep.huntingBoxFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.shardValueSort", "gankura.config.interfaceSettings.sep.huntingBoxFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableHeartMenuTweaks", "gankura.config.interfaceSettings.sep.heartFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightHeartStatus", "gankura.config.interfaceSettings.sep.heartFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showHeartLevel", "gankura.config.interfaceSettings.sep.heartFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enableEnchantedBookSlots", "gankura.config.interfaceSettings.sep.enchantedBookFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showEnchantedBookName", "gankura.config.interfaceSettings.sep.enchantedBookFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showEnchantedBookTier", "gankura.config.interfaceSettings.sep.enchantedBookFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.enablePetTweaks", "gankura.config.interfaceSettings.sep.petFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.highlightActivePet", "gankura.config.interfaceSettings.sep.petFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.showPetLevel", "gankura.config.interfaceSettings.sep.petFolder");
        GROUP_OF.put("gankura.config.interfaceSettings.hideMaxedPetLevel", "gankura.config.interfaceSettings.sep.petFolder");
        GROUP_OF.put("gankura.config.keybinds.enableOpenMenuKeybind", "gankura.config.keybinds.sep.openMenuKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.openLoadoutsKeybind", "gankura.config.keybinds.sep.openMenuKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.openWardrobeKeybind", "gankura.config.keybinds.sep.openMenuKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.openEquipmentKeybind", "gankura.config.keybinds.sep.openMenuKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.enableLoadoutsKeybind", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot1", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot2", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot3", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot4", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot5", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot6", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot7", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot8", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot9", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot10", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot11", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.loadoutsKeybindSlot12", "gankura.config.keybinds.sep.loadoutsKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.enableArmorSetKeybind", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot1", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot2", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot3", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot4", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot5", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot6", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot7", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot8", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.armorSetKeybindSlot9", "gankura.config.keybinds.sep.armorSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.enableEquipmentSetKeybind", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot1", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot2", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot3", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot4", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot5", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot6", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot7", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot8", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.keybinds.equipmentSetKeybindSlot9", "gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        GROUP_OF.put("gankura.config.misc.showEtherwarpTarget", "gankura.config.misc.sep.etherwarpFolder");
        GROUP_OF.put("gankura.config.misc.etherwarpOnlySneaking", "gankura.config.misc.sep.etherwarpFolder");
        GROUP_OF.put("gankura.config.misc.showEtherwarpReason", "gankura.config.misc.sep.etherwarpFolder");
    }

    private static void groups() {
        ALL.add("gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.golemRareDropFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.golemRareDropFolder", "gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.worldLocationFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.worldLocationFolder", "gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.stage4Folder");
        PARENT.put("gankura.config.combat.theEnd.sep.stage4Folder", "gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.stage5Folder");
        PARENT.put("gankura.config.combat.theEnd.sep.stage5Folder", "gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.golemChatFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.golemChatFolder", "gankura.config.combat.theEnd.sep.golemSection");
        ALL.add("gankura.config.combat.theEnd.sep.dragonSection");
        ALL.add("gankura.config.combat.theEnd.sep.dragonRareDropFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.dragonRareDropFolder", "gankura.config.combat.theEnd.sep.dragonSection");
        ALL.add("gankura.config.combat.theEnd.sep.spawnTitleFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.spawnTitleFolder", "gankura.config.combat.theEnd.sep.dragonSection");
        ALL.add("gankura.config.combat.theEnd.sep.dragonChatFolder");
        PARENT.put("gankura.config.combat.theEnd.sep.dragonChatFolder", "gankura.config.combat.theEnd.sep.dragonSection");
        ALL.add("gankura.config.combat.spidersDen.sep.broodmotherSection");
        ALL.add("gankura.config.combat.spidersDen.sep.broodmotherStage4Folder");
        PARENT.put("gankura.config.combat.spidersDen.sep.broodmotherStage4Folder", "gankura.config.combat.spidersDen.sep.broodmotherSection");
        ALL.add("gankura.config.combat.spidersDen.sep.broodmotherStage5Folder");
        PARENT.put("gankura.config.combat.spidersDen.sep.broodmotherStage5Folder", "gankura.config.combat.spidersDen.sep.broodmotherSection");
        ALL.add("gankura.config.combat.spidersDen.sep.broodmotherChatFolder");
        PARENT.put("gankura.config.combat.spidersDen.sep.broodmotherChatFolder", "gankura.config.combat.spidersDen.sep.broodmotherSection");
        ALL.add("gankura.config.combat.spidersDen.sep.arachneSection");
        ALL.add("gankura.config.combat.spidersDen.sep.arachneWorldLocationFolder");
        PARENT.put("gankura.config.combat.spidersDen.sep.arachneWorldLocationFolder", "gankura.config.combat.spidersDen.sep.arachneSection");
        ALL.add("gankura.config.combat.crimsonIsle.sep.crimsonRareDropFolder");
        ALL.add("gankura.config.combat.crimsonIsle.sep.crimsonWorldLocationFolder");
        ALL.add("gankura.config.combat.crimsonIsle.sep.magmaBossSection");
        ALL.add("gankura.config.farming.sep.dnaFolder");
        ALL.add("gankura.config.farming.garden.sep.visitorFolder");
        ALL.add("gankura.config.farming.garden.sep.visitorTitleFolder");
        PARENT.put("gankura.config.farming.garden.sep.visitorTitleFolder", "gankura.config.farming.garden.sep.visitorFolder");
        ALL.add("gankura.config.farming.garden.sep.contestFolder");
        ALL.add("gankura.config.farming.garden.sep.pestFolder");
        ALL.add("gankura.config.farming.garden.sep.pestTitleFolder");
        PARENT.put("gankura.config.farming.garden.sep.pestTitleFolder", "gankura.config.farming.garden.sep.pestFolder");
        ALL.add("gankura.config.farming.garden.sep.vacuumFolder");
        PARENT.put("gankura.config.farming.garden.sep.vacuumFolder", "gankura.config.farming.garden.sep.pestFolder");
        ALL.add("gankura.config.farming.garden.sep.mousematFolder");
        ALL.add("gankura.config.foraging.sep.titleFolder");
        ALL.add("gankura.config.foraging.sep.torrhusCanyonFolder");
        ALL.add("gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.honeybugFolder");
        PARENT.put("gankura.config.foraging.sep.honeybugFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.scrappyFolder");
        PARENT.put("gankura.config.foraging.sep.scrappyFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.rockmiteFolder");
        PARENT.put("gankura.config.foraging.sep.rockmiteFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.wumpaFolder");
        PARENT.put("gankura.config.foraging.sep.wumpaFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.doomspiralFolder");
        PARENT.put("gankura.config.foraging.sep.doomspiralFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.foraging.sep.macawFolder");
        PARENT.put("gankura.config.foraging.sep.macawFolder", "gankura.config.foraging.sep.critterSafariFolder");
        ALL.add("gankura.config.fishing.sep.fishingHudFolder");
        ALL.add("gankura.config.fishing.sep.fishingChatFolder");
        ALL.add("gankura.config.fishing.sep.baitLowAlertFolder");
        ALL.add("gankura.config.fishing.sep.castTimerFolder");
        ALL.add("gankura.config.fishing.sep.hotspotFolder");
        ALL.add("gankura.config.fishing.sep.hotspotGuessFolder");
        PARENT.put("gankura.config.fishing.sep.hotspotGuessFolder", "gankura.config.fishing.sep.hotspotFolder");
        ALL.add("gankura.config.fishing.sep.hotspotCircleFolder");
        PARENT.put("gankura.config.fishing.sep.hotspotCircleFolder", "gankura.config.fishing.sep.hotspotFolder");
        ALL.add("gankura.config.fishing.sep.hotspotFoundFolder");
        PARENT.put("gankura.config.fishing.sep.hotspotFoundFolder", "gankura.config.fishing.sep.hotspotFolder");
        ALL.add("gankura.config.fishing.sep.lavaTextureFolder");
        ALL.add("gankura.config.fishing.sep.goldenFishFolder");
        ALL.add("gankura.config.mining.sep.commissionFolder");
        ALL.add("gankura.config.mining.sep.mineshaftFolder");
        ALL.add("gankura.config.mining.sep.corpseFolder");
        PARENT.put("gankura.config.mining.sep.corpseFolder", "gankura.config.mining.sep.mineshaftFolder");
        ALL.add("gankura.config.mining.sep.wishingCompassFolder");
        ALL.add("gankura.config.generalHud.sep.armorHudFolder");
        ALL.add("gankura.config.generalHud.sep.equipmentHudFolder");
        ALL.add("gankura.config.generalHud.sep.yawPitchHudFolder");
        ALL.add("gankura.config.mobVisuals.sep.theEndFolder");
        ALL.add("gankura.config.mobVisuals.sep.spidersDenFolder");
        ALL.add("gankura.config.mobVisuals.sep.crimsonIsleFolder");
        ALL.add("gankura.config.mobVisuals.sep.crystalHollowsFolder");
        ALL.add("gankura.config.mobVisuals.sep.moongladeMarshFolder");
        ALL.add("gankura.config.mobVisuals.sep.torrhusCanyonFolder");
        ALL.add("gankura.config.mobVisuals.sep.lotusAtollFolder");
        ALL.add("gankura.config.mobVisuals.sep.glaciteMineshaftFolder");
        ALL.add("gankura.config.mobVisuals.sep.gardenFolder");
        ALL.add("gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.hideCapturedFolder");
        PARENT.put("gankura.config.mobVisuals.sep.hideCapturedFolder", "gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.keepShownFolder");
        PARENT.put("gankura.config.mobVisuals.sep.keepShownFolder", "gankura.config.mobVisuals.sep.hideCapturedFolder");
        ALL.add("gankura.config.mobVisuals.sep.safariCavernFolder");
        PARENT.put("gankura.config.mobVisuals.sep.safariCavernFolder", "gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.safariForestFolder");
        PARENT.put("gankura.config.mobVisuals.sep.safariForestFolder", "gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.safariHauntedFolder");
        PARENT.put("gankura.config.mobVisuals.sep.safariHauntedFolder", "gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.safariIcyFolder");
        PARENT.put("gankura.config.mobVisuals.sep.safariIcyFolder", "gankura.config.mobVisuals.sep.critterSafariFolder");
        ALL.add("gankura.config.mobVisuals.sep.seaCreatureFolder");
        ALL.add("gankura.config.interfaceSettings.sep.betterInventoryFolder");
        ALL.add("gankura.config.interfaceSettings.sep.tabListFolder");
        ALL.add("gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        ALL.add("gankura.config.interfaceSettings.sep.enchantTooltipFolder");
        PARENT.put("gankura.config.interfaceSettings.sep.enchantTooltipFolder", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        ALL.add("gankura.config.interfaceSettings.sep.itemPriceFolder");
        PARENT.put("gankura.config.interfaceSettings.sep.itemPriceFolder", "gankura.config.interfaceSettings.sep.tooltipPositionFolder");
        ALL.add("gankura.config.interfaceSettings.sep.auctionBazaarFolder");
        ALL.add("gankura.config.interfaceSettings.sep.attributeFolder");
        ALL.add("gankura.config.interfaceSettings.sep.bestiaryFolder");
        ALL.add("gankura.config.interfaceSettings.sep.huntingBoxFolder");
        ALL.add("gankura.config.interfaceSettings.sep.heartFolder");
        ALL.add("gankura.config.interfaceSettings.sep.enchantedBookFolder");
        ALL.add("gankura.config.interfaceSettings.sep.petFolder");
        ALL.add("gankura.config.keybinds.sep.openMenuKeybindFolder");
        ALL.add("gankura.config.keybinds.sep.loadoutsKeybindFolder");
        ALL.add("gankura.config.keybinds.sep.armorSetKeybindFolder");
        ALL.add("gankura.config.keybinds.sep.equipmentSetKeybindFolder");
        ALL.add("gankura.config.misc.sep.etherwarpFolder");
    }
}
